"""Reference multizone profiles from Kodavasal et al. (2013, JER 10.1177/1468087413482480).

Supported zone counts are fixed to the paper's published presets:
- Figure 2: prescribed zone mass fractions (10, 20, and 40 zones)
- Figure 3(b): zone heat-loss multiplier curve (40 zones)
- 20-zone multipliers are generated by cumulative-mass remapping of the
  published 40-zone Figure 3(b) curve onto the Figure 2 20-zone bins,
  with a mild monotonic wall-tail emphasis for numerical/behavioral balance.
"""

from __future__ import annotations

import numpy as np

SUPPORTED_MULTIZONE_COUNTS = (10, 20, 40)

# Figure 2 (10-zone) mass fractions, ordered from hottest (zone 1/core)
# to coldest (zone 10/wall-adjacent).
_FIG2_MASS_FRACTIONS_10 = np.array(
    [0.02, 0.08, 0.10, 0.10, 0.20, 0.20, 0.10, 0.10, 0.08, 0.02],
    dtype=float,
)

# Figure 2 (20-zone) mass fractions read from the plotted step profile.
_FIG2_MASS_FRACTIONS_20 = np.array(
    [
        0.01, 0.02, 0.02, 0.05, 0.05, 0.05, 0.05, 0.05, 0.10, 0.10,
        0.10, 0.10, 0.05, 0.05, 0.05, 0.05, 0.05, 0.02, 0.02, 0.01,
    ],
    dtype=float,
)

# Figure 2 (40-zone) mass fractions read from the plotted step profile.
_FIG2_MASS_FRACTIONS_40 = np.array(
    [0.005] * 2
    + [0.01] * 4
    + [0.025] * 10
    + [0.05] * 8
    + [0.025] * 10
    + [0.01] * 4
    + [0.005] * 2,
    dtype=float,
)

# Existing 10-zone heat-loss multipliers already in use in this codebase.
# These are normalized downstream by mass weighting.
_FIG3B_HEAT_MULT_10_RAW = np.array(
    [0.08, 0.22, 0.38, 0.55, 0.75, 1.00, 1.35, 1.85, 2.90, 7.70],
    dtype=float,
)

# Figure 3(b) (40-zone): digitized from the published curve.
# The final three wall-adjacent points follow the distinct high-C_i tail.
_FIG3B_HEAT_MULT_40_RAW = np.array(
    [
        0.050, 0.068, 0.085, 0.102, 0.120, 0.156, 0.192, 0.228, 0.264, 0.300,
        0.340, 0.380, 0.420, 0.460, 0.500, 0.550, 0.600, 0.650, 0.700, 0.750,
        0.833, 0.917, 1.000, 1.070, 1.140, 1.210, 1.280, 1.350, 1.475, 1.600,
        1.725, 1.850, 2.133, 2.417, 2.700, 2.850, 3.000, 4.500, 6.800, 7.700,
    ],
    dtype=float,
)


def validate_multizone_count(nzones: int) -> int:
    """Validate and return a supported multizone count."""
    nzones = int(nzones)
    if nzones not in SUPPORTED_MULTIZONE_COUNTS:
        supported = ", ".join(str(v) for v in SUPPORTED_MULTIZONE_COUNTS)
        raise ValueError(
            f"Unsupported multizone count: {nzones}. Choose one of: {supported}."
        )
    return nzones


def _remap_profile_by_mass_bins(
    source_values: np.ndarray,
    source_masses: np.ndarray,
    target_masses: np.ndarray,
) -> np.ndarray:
    """Mass-conserving remap from one zone-mass partition to another."""
    src_edges = np.concatenate([[0.0], np.cumsum(source_masses)])
    dst_edges = np.concatenate([[0.0], np.cumsum(target_masses)])
    out = np.zeros_like(target_masses, dtype=float)

    j = 0
    for i in range(len(target_masses)):
        left = dst_edges[i]
        right = dst_edges[i + 1]
        x = left
        accum = 0.0
        while x < right - 1.0e-15:
            while j < len(source_masses) - 1 and src_edges[j + 1] <= x + 1.0e-15:
                j += 1
            seg_right = min(right, src_edges[j + 1])
            dm = seg_right - x
            accum += dm * source_values[j]
            x = seg_right
        out[i] = accum / target_masses[i]
    return out


_FIG3B_HEAT_MULT_20_FROM_40 = _remap_profile_by_mass_bins(
    _FIG3B_HEAT_MULT_40_RAW, _FIG2_MASS_FRACTIONS_40, _FIG2_MASS_FRACTIONS_20
)
# Mild rebalance for 20 zones:
# keep Figure-3(b) 40->20 remap as baseline and apply a small monotonic
# wall-tail emphasis to counter 20-zone discretization bias in peak pressure.
_ZONE_IDX_20 = np.linspace(0.0, 1.0, len(_FIG3B_HEAT_MULT_20_FROM_40))
_FIG3B_HEAT_MULT_20_RAW = (
    (_FIG3B_HEAT_MULT_20_FROM_40 ** 1.05) * (0.975 + 0.05 * _ZONE_IDX_20)
)

_MASS_FRACTION_PROFILES = {
    10: _FIG2_MASS_FRACTIONS_10,
    20: _FIG2_MASS_FRACTIONS_20,
    40: _FIG2_MASS_FRACTIONS_40,
}

_HEAT_MULTIPLIER_PROFILES = {
    10: _FIG3B_HEAT_MULT_10_RAW,
    20: _FIG3B_HEAT_MULT_20_RAW,
    40: _FIG3B_HEAT_MULT_40_RAW,
}


def _normalize_mass_weighted_multipliers(mass_fracs: np.ndarray, multipliers: np.ndarray) -> np.ndarray:
    """Normalize multipliers so mass-weighted average is 1."""
    denom = float(np.dot(mass_fracs, multipliers))
    if denom <= 0.0:
        return np.ones_like(multipliers)
    return multipliers / denom


def zone_mass_fractions(nzones: int) -> np.ndarray:
    """Return per-zone mass fractions (sum=1)."""
    nzones = validate_multizone_count(nzones)
    return _MASS_FRACTION_PROFILES[nzones].copy()


def zone_heat_loss_multipliers(nzones: int, mass_fracs: np.ndarray) -> np.ndarray:
    """Return normalized per-zone heat-loss multipliers C_i."""
    nzones = validate_multizone_count(nzones)
    return _normalize_mass_weighted_multipliers(
        mass_fracs, _HEAT_MULTIPLIER_PROFILES[nzones]
    )
